### PR TITLE
Native Websocket Client

### PR DESCRIPTION
**Pull request by prom3theu5**
Also Updated Client Test project

### CODE REVIEW

**Comment by prom3theu5** [comment]
Thanks mate :)
Just implemented a throttler similar to the old one directly on the Socket.
Values can be changed in the passed in Options class

**Comment by Syzuna** [comment]
Shouldnt this PR be in the TwitchLib.Client package Not in the Main one?

**Comment by prom3theu5** [comment]
No Man.
Both Client and PubSub use the WebSocketClient, so it's got to be part of the main repo like the others are. I'm guessing it'll be split off into a submodule once it's fully tested.

**Comment by Syzuna** [comment]
Ok yeah I get that but you also changed stuff in the client and pubsub itself right?

**Comment by prom3theu5** [comment]
I have done aye - but those commits are pushed against the Sub Modules directly
I can PR them separately

**Comment by prom3theu5** [comment]
Sorted @Syzuna :)

**Pull request closed without merging**
